[package]
name = "fcast-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = "0.1.19"
anyhow = { workspace = true }
tokio = { workspace = true }