import { HorizontalBox, LineEdit, VerticalBox } from "std-widgets.slint";

export component LabeledLineEdit {
    in property <string> label <=> text.text;
    in property <string> placeholder-text <=> line.placeholder-text;
    in property <InputType> input-type <=> line.input-type;
    in-out property <string> text <=> line.text;

    HorizontalBox {
        text := Text {
            vertical-alignment: center;
        }

        line := LineEdit {}
    }
}

export component NetworkPortInput {
    in property <string> label <=> input.label;
    in-out property <string> text <=> input.text;

    pure function is-valid-port-number(port: int) -> bool {
        port >= 1 && port <= 65535
    }

    VerticalLayout {
        width: 100%;

        input := LabeledLineEdit {
            input-type: number;
        }

        if !is-valid-port-number(root.text.to-float()): Text {
            horizontal-alignment: center;
            text: "Port is not in the valid range (1-65535)";
        }
    }
}
