// Copyright (C) 2025 Marcus L. Hanestad <marlhan@proton.me>
//
// This file is part of OpenMirroring.
//
// OpenMirroring is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// OpenMirroring is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with OpenMirroring.  If not, see <https://www.gnu.org/licenses/>.

import { Palette } from "std-widgets.slint";

// TODO: Fiz z axis
export component ToolTipArea {
    in property <string> text;

    z: 100;

    ta := TouchArea {
        @children

        Rectangle {
            states [
                visible when ta.has-hover: {
                    opacity: 1.0;
                    in {
                        animate opacity {
                            duration: 0ms;
                            delay: 600ms;
                        }
                    }
                }
            ]

            // Add 8px to give some space between the cursor and the rect
            x: ta.mouse-x + 8px;
            y: ta.mouse-y + 8px;

            background: Palette.alternate-background;
            opacity: 0;
            border-radius: 8px;
            width: tt_l.preferred-width;
            height: tt_l.preferred-height;
            tt_l := HorizontalLayout {
                padding: 10px;
                Text {
                    text <=> root.text;
                }
            }
        }
    }
}
