// Copyright (C) 2025 Marcus L. Hanestad <marlhan@proton.me>
//
// This file is part of OpenMirroring.
//
// OpenMirroring is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// OpenMirroring is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with OpenMirroring.  If not, see <https://www.gnu.org/licenses/>.

import { Spinner, HorizontalBox, Button, Palette, VerticalBox } from "std-widgets.slint";
import { HorizontalRule } from "../../ui-common/horizontal-rule.slint";

// TODO: animate in and out transitions
component ErrorAlert {
    in property <string> message;

    visible: false;

    public function show() {
        self.visible = true;
        timer.counter = 0;
        timer.running = true;
    }

    function close() {
        self.visible = false;
        timer.running = true;
    }

    states [
        hover when ta.has-hover : {
            im.colorize: #DEDEDE;
        }
    ]

    Rectangle {
        height: hb.preferred-height;
        background: #FF4131;
        border-radius: 8px;

        hb := HorizontalBox {
            alignment: space-between;
            Text {
                color: white;
                vertical-alignment: center;
                text <=> message;
                wrap: word-wrap;
                font-weight: 800;
            }
            ta := TouchArea {
                height: 32px;
                width: 32px;
                clicked => {
                    root.close();
                }
                Rectangle {
                    im := Image {
                        height: 100%;
                        source: @image-url("../../assets/icons/xmark.svg");
                        colorize: white;
                        animate colorize { duration: 150ms; }
                    }
                }
            }
        }
    }

    timer := Timer {
        in-out property <int> counter: 0;
        interval: 1s;
        running: true;
        triggered => {
            counter += 1;
            if counter >= 4 {
                root.close();
            }
        }
    }
}

export component MainWindow inherits Window {
    title: "Open Mirroring Receiver";

    in property <string> label;
    in property <image> preview-frame <=> preview.source;

    in-out property <bool> playing: false;

    property <int> connected_devices: 0;

    public function playback-started() {
        playing = true;
    }

    public function playback-stopped() {
        playing = false;
    }

    public function playback-stopped-with-error(error: string) {
        playing = false;
        error-alert.message = error;
        error-alert.show();
    }

    public function device-connected() {
        connected_devices += 1;
    }

    public function device-disconnected() {
        connected_devices = max(connected_devices - 1, 0);
    }

    HorizontalBox {
        alignment: space-around;
        if connected_devices == 0: VerticalBox {
            alignment: center;
            Text {
                font-size: 12pt;
                text: "Waiting for a connection";
            }
            Spinner {
                indeterminate: true;
            }
        }
        if connected_devices > 0: VerticalBox {
            alignment: center;
            Text {
                font-size: 12pt;
                text: "Device is connected";
            }
        }

        VerticalBox {
            alignment: center;
            Rectangle {
                background: whitesmoke.with-alpha(60%);
                border-radius: 8px;
                border-color: white.with-alpha(60%);
                border-width: 2px;
                VerticalBox {
                    Text {
                        horizontal-alignment: center;
                        text: "Manual connection information";
                        font-size: 12pt;
                    }
                    HorizontalRule {
                        color: white.with-alpha(60%);
                        height: 2px;
                    }
                    Text {
                        horizontal-alignment: center;
                        text: "IPs";
                    }
                    if !playing && label.is-empty: Spinner {
                        indeterminate: true;
                    }
                    if !playing && !label.is-empty: Text {
                        horizontal-alignment: center;
                        text <=> label;
                    }
                    Text {
                        horizontal-alignment: center;
                        text: "Port";
                    }
                    Text {
                        horizontal-alignment: center;
                        text: "46899 (TCP)";
                    }
                    Text {
                        horizontal-alignment: center;
                        text: "Automatic discovery is available via mDNS";
                    }
                }
            }
        }
    }

    Rectangle {
        visible: playing;
        width: 100%;
        height: 100%;
        background: black;

        preview := Image {
            width: 100%;
            height: parent.height;
            image-fit: contain;
        }
    }

    error-alert := ErrorAlert {
        width: min(parent.width * 0.8, 700px);
        y: parent.height - self.height - 20px;
    }
}
