import { Spinner } from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "Open Mirroring Receiver";

    in property <bool> playing: false;
    in property <string> label;
    // property <bool> playing: true;
    in property <image> preview-frame <=> preview.source;

    Spinner {
        visible: !playing && label.is-empty;
        indeterminate: true;
    }

    Text {
        visible: !playing && !label.is-empty;
        text <=> label;
    }

    Rectangle {
        visible: playing;
        width: 100%;
        height: 100%;
        background: black;

        preview := Image {
            width: 100%;
            height: parent.height;
            image-fit: contain;
        }
    }
}
