// Copyright (C) 2025 Marcus L. Hanestad <marlhan@proton.me>
//
// This file is part of OpenMirroring.
//
// OpenMirroring is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// OpenMirroring is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with OpenMirroring.  If not, see <https://www.gnu.org/licenses/>.

import { Palette, Switch, HorizontalBox } from "std-widgets.slint";

export component VideoPreview inherits Rectangle {
    in-out property <bool> show-preview;

    ta := TouchArea {
        pointer-event(event) => {
            if event.button == PointerEventButton.right && event.kind == PointerEventKind.down {
                dialog.show();
            }
        }
    }

    @children

    Rectangle {
        visible: !show-preview;

        Text {
            text: "Preview disabled";
        }
    }

    dialog := PopupWindow {
        x: ta.mouse-x;
        y: ta.mouse-y;

        Rectangle {
            background: Palette.alternate-background;
            border-radius: 8px;

            Dialog {
                HorizontalBox {
                    Text {
                        vertical-alignment: center;
                        text: "Show preview";
                    }
                    Switch {
                        checked: show-preview;
                        toggled => {
                            show-preview = !show-preview;
                        }
                    }
                }
            }
        }
    }
}
