[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
slint = { workspace = true }
gst-gl = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
gio = { version = "0.20.9", optional = true }
m3u8-rs = { version = "6.0.0", optional = true }
http = { path = "../http", optional = true }
futures = { workspace = true, optional = true }
async-tungstenite = { git = "https://github.com/MAlba124/async-tungstenite.git", rev = "96b8e852d08b33825388824148c80b689d6ec9db", features = ["tokio-runtime"], optional = true }
uuid = { version = "1", features = ["v4"], optional = true }
pin-project-lite = { version = "0.2", optional = true }
bytes = { version = "1.10.1", optional = true }
async-trait = { version = "0.1.88", optional = true }
gst-video = { workspace = true, optional = true, features = [ "v1_24" ] }
gst-pbutils = { package = "gstreamer-pbutils", version = "0.23.5", features = [ "v1_24" ], optional = true }
gst = { workspace = true, optional = true, features = [ "v1_24" ] }
gst-app = { workspace = true, optional = true, features = [ "v1_24" ] }
fcast-lib = { path = "../fcast-lib", optional = true }
tokio-stream = { workspace = true, optional = true }

[target.'cfg(target_os = "android")'.dependencies]
crossbeam-channel = { version = "0.5.15", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.60.0", features = ["Win32_Networking_WinSock", "Win32_NetworkManagement_Ndis", "Win32_NetworkManagement_IpHelper"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
pnet_datalink = "0.35.0"
ipnetwork = "0.20.0"

[target.'cfg(target_os = "linux")'.dependencies]
gst-gl-egl = { package = "gstreamer-gl-egl", version = "0.23.5" }
gst-gl-x11 = { package = "gstreamer-gl-x11", version = "0.23.5" }
glutin_egl_sys = "0.7.1"
glutin_glx_sys = "0.6.1"

[features]
video = ["gst", "gst-app", "gst-video", "gst-gl"]
sender = ["gst", "gst-video", "serde", "serde_json", "gio", "m3u8-rs", "gst-pbutils",
        "http", "futures", "async-tungstenite", "uuid", "pin-project-lite",
        "bytes", "async-tungstenite", "async-trait", "crossbeam-channel", "gst-app",
        "fcast-lib", "tokio-stream"]

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"